#!/bin/bash

sh final_scripts/blur_ablation_pacs_alexnet/dann_alexnet_with_blur/dann_with_blur_rs16.sh
sh final_scripts/blur_ablation_pacs_alexnet/dann_alexnet_with_blur/dann_with_blur_rs33.sh
sh final_scripts/blur_ablation_pacs_alexnet/dann_alexnet_with_blur/dann_with_blur_rs51.sh